
/* Drop Tables */

DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE SELLER CASCADE CONSTRAINTS;
DROP TABLE FOODTRUCKS CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE CUSTOMER
(
	G_NO varchar2(10) NOT NULL,
	ID varchar2(10) NOT NULL UNIQUE,
	PWD varchar2(10) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	REGIDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (G_NO)
);


CREATE TABLE FOODTRUCKS
(
	F_NO varchar2(10) NOT NULL,
	TNAME nvarchar2(15) NOT NULL,
	ADDR nvarchar2(50) NOT NULL,
	TEL nvarchar2(15) NOT NULL,
	CORPORATE_NO nvarchar2(12) NOT NULL,
	PRIMARY KEY (F_NO)
);


CREATE TABLE SELLER
(
	S_NO varchar2(10) NOT NULL,
	F_NO varchar2(10) NOT NULL,
	ID varchar2(10) NOT NULL UNIQUE,
	PWD varchar2(10) NOT NULL,
	NAME nvarchar2(10) NOT NULL,
	REGIDATE date NOT NULL,
	PRIMARY KEY (S_NO)
);



/* Create Foreign Keys */

ALTER TABLE SELLER
	ADD FOREIGN KEY (F_NO)
	REFERENCES FOODTRUCKS (F_NO)
;



